### ISSUE TITLE
Colab 포스팅 Pytorch 설치 관련

### ISSUE THREAD

**Issue by KyungheeKo** [20-2-SKKU-OSS/2020-2-OSS-10#11]
[Colab 포스팅](https://github.com/20-2-SKKU-OSS/2020-2-OSS-10/blob/main/_posts/2020-12-04-Colab.md) 에서 Pytorch를 별도로 설치해야한다는 것은 과거의 정보로 보입니다. 현재에는 Colab이 Pytorch를 지원하고 있고, 아래 사진과 같이 import torch 만으로도 충분히 사용이 가능합니다.

![image](https://user-images.githubusercontent.com/62197187/101238245-3e62a500-3722-11eb-8c7e-efc6255abbcf.png)

따라서 해당 정보의 수정을 요청드립니다. 그렇지만 package의 설치와 관련된 부분이 불필요한 정보는 아니므로, 되도록 Colab에서 지원하지 않는 다른 패키지를 설치해보는 방식으로 수정해주시면 감사하겠습니다.

**Comment by SongJae** [comment]
해당 내용을 수정하고 새롭운 package 설치 예시를 추가하였습니다.
감사합니다.
